name: workflow_1
on: push
jobs:
	job1:
		runs-on: ubuntu-latest
		steps:
			- name: step-1
			  run: exit 1
			  continue-on-error: true
			- name: step-2
			  run: echo "This is step-2"
			- name: step-3
			  if: failure()
			  run: echo "step-1 is considered as failure"